name: cinehanzo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  google_fonts: ^6.2.1
  dio: ^5.5.0+1
  introduction_screen: ^3.1.14
  flutter_svg: ^2.0.10+1
  flutter_modular: ^6.3.4
  shared_preferences: ^2.2.3
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  google_sign_in: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - lib/core/ui/images/
